### ISSUE TITLE
can i help?

### ISSUE THREAD

**Issue by AdamEXu** [sneakymod/sneakyLoader#1]
i know how to decompile game and have access to the game's source code and assets :D

**Comment by AdamEXu** [comment]
count in https://github.com/Roizor too!

**Comment by AdamEXu** [comment]
also since you haven't even started I can give what I have already

**Comment by BlueFalconHD** [comment]
Join this discord and tell me your name. We will discuss there, in private.

**Comment by BlueFalconHD** [comment]
Gert, if you are reading this, know my intentions were not to ask for decompiled source or anything. All I did was ask them to stop decompiling the game and cheating. I feel that I have similar ideals to yours in that respect.
